name: schedule

# 当push到main分支和定时时间时触发任务
on:
  push:
    branches: [ main ]
  schedule:
    # 东八区09:00，约莫有延时10~20，看github服务器情况
    - cron: ' 0 1 * * *'

jobs:
  # 自动打卡任务
  autocard:
    # 使用ubuntu作为运行的OS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # 安装java环境
      - name: "Setup Java"
        uses: actions/setup-java@v2
        with:
           distribution: 'temurin'
           java-version: '17'

      # 执行打卡
      - name: "Run AutoCard"
        run: cd action && java  --add-opens java.base/java.lang=ALL-UNNAMED -jar autocard-1.4.1.jar --app.autoCard.immediate=true
