name: schedule

# 任务触发
on:
  # 当 提交到当前仓库时立即运行
  push:
    branches: [ main ]
  schedule:
    # 东八区09:00，约莫有延时10~20，看github服务器情况
    - cron: ' 0 1 * * *'
  
  # 当star当前仓库时立即执行
  watch:
    types: [started]

jobs:
  # 自动打卡任务
  autocard:
    # 使用ubuntu作为运行的OS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # 安装java环境
      - name: "Setup Java"
        uses: actions/setup-java@v2
        with:
           distribution: 'temurin'
           java-version: '17'
      
      # 缓存信息，当缓存发生变化时，请修改key值
      - name: "Cache autocard cache file"
        uses: actions/cache@v3
        with: 
          key: "autocard_cache"
          path: "action/autocard_cache.json"
            
      # 执行打卡
      - name: "Run AutoCard"
        env: 
          AUTOCARD_USER: ${{ secrets.AUTOCARD_USER }}
          AUTOCARD_PWD: ${{ secrets.AUTOCARD_PWD }}
          AUTOCARD_DINGTALK_URL: ${{ secrets.AUTOCARD_DINGTALK_URL }}
          AUTOCARD_DINGTALK_SECRET: ${{ secrets.AUTOCARD_DINGTALK_SECRET }}
        run: cd action && java  --add-opens java.base/java.lang=ALL-UNNAMED -jar autocard.jar --app.autoCard.immediate=true
